### PR TITLE
Node.js 4

### PR DESCRIPTION
**Pull request by jonnor**

### CODE REVIEW

**Comment by jonnor** [comment]
@automata what do you think can be the cause of these failures, and do you consider them critical?

**Comment by automata** [comment]
@jonnor those failures show values not that different from what is expected, but I'll take a look on that closely before we do changes on tests or components themselves. What bothers me is why we're getting those values now and what changed on node-canvas, jsfeat or somewhere else that gives those values now.

BTW they're only related with jsfeat the first test, right? Maybe we should bump jsfeat too.

**Comment by jonnor** [comment]
jsfeat has not changed. I suspect the changes come from node-canvas, but I have not checked

**Comment by automata** [comment]
@jonnor it's green now.

**Pull request merged**
