### PR TITLE
Make color quantization async using nextTick queue

### PR DESCRIPTION
**Pull request by automata**
Fallbacks to `setTimeout` when `process.nextTick` is not available (e.g. browsers).

### CODE REVIEW

**Comment by automata** [comment]
@GabiThume simple workaround, can you review/merge please?

**Comment by bergie** [comment]
Note that just `nextTick` doesn't make it "real async". It means the result will be sent out at next cycle of the event loop, but if RgbQuant blocks event loop, this has little benefit

**Comment by automata** [comment]
@bergie right, I was following [this suggestion](https://github.com/leeoniya/RgbQuant.js/issues/20#issuecomment-153738346) by authors since RgbQuant is not blocked by IO events. So either we change RgbQuant or downscale the image, so at least we prevent it being blocked by large images.

**Comment by automata** [comment]
Since this PR has no real effect and is dependent on RgbQuant itself, I'm closing it for now.

**Comment by leeoniya** [comment]
It's a crying shame that Web Workers are so neutered [1] and can't load images or create canvas objects. The blatantly obvious use case for image processing has to be done by creating a canvas on the main DOM/UI thread, drawing an image to it and passing the pixel data via `postMessage`. I personally don't understand how things have still not improved. I guess we have Transferrable Objects [2] now and WebGL (where a huge increase can be attained if we rewrite all the things).

[1] http://stackoverflow.com/questions/14785761/limitations-of-web-workers/14785778#14785778
[2] https://developer.mozilla.org/en-US/docs/Web/API/Transferable

**Comment by jonnor** [comment]
@automata has a feature request been filed on RGBQuant?

**Comment by automata** [comment]
@jonnor https://github.com/leeoniya/RgbQuant.js/issues/20

**Pull request closed without merging**
